### ISSUE TITLE
Add android example

### ISSUE THREAD

**Issue by xcarpentier** [expo/detox-expo-helpers#2]

**Comment by brentvatne** [comment]
can you try to figure it out? on vacation for 2 weeks. let me know :)

**Comment by conblem** [comment]
I have been trying to figure this out, but i'm currently stuck on this error.
[Repository](https://github.com/conblem/bs.li/tree/detox)

```
  console.error node_modules\react-native\Libraries\Core\ExceptionsManager.js:73
    Unhandled error

  console.error node_modules\react-native\Libraries\Core\ExceptionsManager.js:73
    Error: spawn adb ENOENT
        at _errnoException (util.js:1021:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
        at onErrorNT (internal/child_process.js:374:16)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)

```

To make it, to this error the Expo APK needs to be placed into the root of the project, with the original name and also as a duplicate, with the name `Exponent-2.0.0-androidTest.apk`.

The APK for Expo can be found on their [website](https://expo.io/tools).
[Exponent-2.0.0.apk](https://d1ahtucjixef4r.cloudfront.net/Exponent-2.0.0.apk)

Some help would be appreciated :).

**Comment by conblem** [comment]
@brentvatne

**Comment by brentvatne** [comment]
@conblem - not familiar with that error, looks like `adb` isn't in your PATH

**Comment by conblem** [comment]
@brentvatne Yeah thats what i thought too but its definitely in my path.

**Comment by ararog** [comment]
At first I had only ANDROID_HOME set, but once I've added $ANDROID_HOME/platform-tools to the path I could get rid of this message about adb.

**Comment by conblem** [comment]
@ararog will try this out, thanks for the hint 👍

**Comment by brentvatne** [comment]
we're investigating this currently, I think it's not so straightforward, cc @esamelson

**Comment by esamelson** [comment]
yeah the plan is to PR a few things to detox to make it work better with expo. Currently detox makes a number of assumptions about RN apps that expo doesn't follow, which makes it difficult to integrate as it is. Hopefully we'll get to this soon, so stay tuned 👍

**Comment by nykolaslima** [comment]
@esamelson do you have any update on this?
If you have any guide about how to help implementing this, we're starting a expo/react native application but we're worried about how to run e2e tests and Detox looks like a better solution but not supported by expo/android apps.

**Comment by esamelson** [comment]
Hi @nykolaslima - no update unfortunately 😞 We have simply not had the time and ability to prioritize this. We'd like to pick this up at some point but it's not on the roadmap at the moment. You'll need to either dig into this yourself or find a different solution for Android for now.

**Comment by maitriyogin** [comment]
Hi, I'm trying to get detox running on android with expo sdk 32.
My basic config is such
```
"android.emu.debug": {
        "binaryPath": "bin/Exponent.apk",
        "type": "android.emulator",
        "name": "Nexus_5X_API_27"
      }
```
Then to run I :

download latest Exponent.apk from expo using a variant of brents script
```
#!/bin/bash -e

# query expo.io to find most recent ipaUrl
IPA_URL=`curl https://expo.io/--/api/v2/versions |  python -c 'import sys, json; print json.load(sys.stdin)["androidUrl"]'`

# download tar.gz
TMP_PATH=bin/Exponent.apk
wget -O $TMP_PATH $IPA_URL
```

`expo start`
`detox test -c android.emu.debug`

Emulator starts up but then nothing...
The setup is the same as with-detox-test and the getting started.
All works amazingly on iOS ...

So, just wondering if I'm being totally nieve or if anyone else out there has managed to get expo working with detox on android ...?
or even where I could start to help out?

Many thanks,
Stephen.

**Comment by aarshaw** [comment]
@maitriyogin were you able to get anything working on Android?

**Comment by maitriyogin** [comment]
Nope, looks like the expo team are working on it or at least aware of it..

**Comment by maitriyogin** [comment]
any news on this expo masters?
/Stephen

**Comment by CorinneKelly** [comment]
@esamelson @brentvatne @conblem (you guys seem to be working on this). Any updates on getting e2e testing on android with expo?

**Comment by esamelson** [comment]
Hey there, this is not something we're actively working on at the moment. Apologies if any previous stale activity in this issue was misleading. You're welcome to dig into this yourself, though, and we're definitely open to accepting a high quality PR or set of PRs adding this functionality!

**Comment by brentvatne** [comment]
indeed, i suggest using the [bare workflow](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/#bare-workflow) if you need to run tests with detox.

**Comment by AizenSousuke** [comment]
Anyone got a solution to this issue on Windows?
